spring:
  application:
    name: validation
server:
  port: 8090
topic:
  trades:
    incoming: tradeHistory
    eligible: eligibleTrades
    management: tradeManagement
group:
  id: test-group-1
trade:
  eligible:
    products: "FX Option, FX Spot, FX Forward, FX Structured Product"

