spring:
  application:
    name: validation
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      properties:
        allow.auto.create.topics: false
      security:
        protocol: PLAINTEXT
    listener:
      missing-topics-fatal: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8090
topic:
  trades:
    input: tradeInput
    incoming: tradeHistory
    eligible: eligibleTrades
    management: tradeManagement
group:
  id: test-group-1
trade:
  eligible:
    products: "FX Option, FX Spot, FX Forward, FX Structured Product"

