spring:
  application:
    name: validation
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      security:
        protocol: PLAINTEXT
server:
  port: 8090
topic:
  trades:
    incoming: tradeHistory
    eligible: eligibleTrades
    management: tradeManagement
group:
  id: test-group-1
trade:
  eligible:
    products: "FX Option, FX Spot, FX Forward, FX Structured Product"

